name: Create documentation

on:
  push:
    branches:
      - develop

jobs:
  concatenate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Concatenate PHP Files
        run: |
          commit_changes=$(git show --stat --patch --no-color HEAD)
          echo "$commit_changes" > docudump.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Ask question to CatGPT
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        run: |
          python - <<EOF
          import openai
          import os

          qtext = open('docudump.txt').read()
          openai.api_key = os.environ['CHATGPT_API_KEY']

          response = openai.ChatCompletion.create(
            engine='text-davinci-002',
            prompt='Explain these code changes in plain text: ' + qtext,
            max_tokens=4096
          )

          print(response.choices[0].text.strip())
          EOF
