name: Create documentation

on:
  push:
    branches:
      - develop

jobs:
  concatenate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Concatenate PHP Files
        run: |
          content=$(cat engine/*.php)
          echo "$content" > docudump.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Ask question to CatGPT
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        run: |
          python - <<EOF
          import openai
          import os

          qtext = open('docudump.txt').read()
          openai.api_key = os.environ['CHATGPT_API_KEY']

          response = openai.Completion.create(
            engine='text-davinci-003',
            prompt='Create a plain text documentation outlining the class and methods in hirearchy from this php script. ' + qtext,
            max_tokens=2000
          )

          print(response.choices[0].text.strip())
          EOF
