name: Create Documentation

on:
  push:
    branches:
      - develop

jobs:
  collect_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    
    - name: Collect PHP files
      id: collect_php_files
      run: |
        php_folder="${{ github.workspace }}/engine
        php_files=$(find "$php_folder" -type f -name "*.php" -print0 | xargs -0 echo)
        echo "PHP_FILES=$php_files" >> $GITHUB_ENV
    
    - name: Display PHP files
      run: |
        echo "PHP files found:"
        echo "${{ env.PHP_FILES }}"