name: Create Documentation

on:
  push:
    branches:
      - develop

jobs:
  collect_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    
    - name: Collect PHP files
      id: collect_php_files
      run: |
        php_folder="${{ github.workspace }}/engine"
        php_files=$(find "$php_folder" -type f -name "*.php" -print0 | xargs -0 echo)
        php_contents=""
        for file in $php_files; do
          content=$(cat "$file")
          php_contents+="$content "
        done
        echo "PHP_CONTENTS=$php_contents" >> $GITHUB_ENV
        echo "QUESTION=$php_contents" >> $GITHUB_ENV
    
    - name: Ask question to ChatGPT
      id: ask_question
      run: |
        response=$(curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer sk-...mbtk" \
          -d '{
            "question": "'"$PHP_CONTENTS"'",
            "max_tokens": 500
          }' \
          https://api.openai.com/v1/engines/davinci-codex/completions)
        
        answer=$(echo "$response" | jq -r '.choices[0].text')
        echo "ANSWER=$answer" >> $GITHUB_ENV
    
    - name: Display Answer
      run: |
        echo "Answer:"
        echo "${{ env.ANSWER }}"
