name: Create documentation

on:
  push:
    branches:
      - develop

jobs:
  concatenate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Concatenate PHP Files
        run: |
          cat engine/*.php >> concatenated.php
          echo "MY_QUESTION=$(cat concatenated.php)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Ask question to CatGPT
        env:
          QUESTION: ${{ env.MY_QUESTION }} 
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        run: |
          python - <<EOF
          import openai
          import os

          question = os.environ['QUESTION']
          openai.api_key = os.environ['CHATGPT_API_KEY']

          response = openai.Completion.create(
            engine='text-davinci-003',
            prompt='Write me each class and its methods into an outline from this php script ' + question,
            max_tokens=4000
          )

          print(response.choices[0].text.strip())
          EOF
